version: "2.4"

services:
  ts:
    build:
      context: .
      target: dev
    ports:
      - "3001:3001"
      - "9229:9229"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    container_name: cdlogs-database
    image: mongo:latest
    restart: always
    volumes:
      - ./cdlogs:/data/db
    environment:
      - MONGO_INITDB_DATABASE=CDlogs
    ports:
      - 27017:27017