import { Document } from 'mongoose'

export interface ISmartlog {
  date: string,
  diver_name: string,
  standby_diver: string,
  diving_supervisor: string,
  diving_contractor: string,
  vessel: string,
  location: string,
  client: string,
  dive_method: string,
  breathing_gas: string,
  leave_surface: string,
  leave_bottom: string,
  bottom_time: number,
  depth: number,
  decompression_completed_at: string,
  post_dive_assesment: string,
  diver_bailout_pressure: number,
  standby_diver_bailout_pressure: number,
  dive_system_id: string,
  work_description: string,
  penetration_diving: string,
  sea_state: string,
  bottom_temperature: string,
  bottom_visibility: string,
  bottom_current: string,
}

export interface ISmartlogModel extends Document {
  date: string,
  diver_name: string,
  standby_diver: string,
  diving_supervisor: string,
  diving_contractor: string,
  vessel: string,
  location: string,
  client: string,
  dive_method: string,
  breathing_gas: string,
  leave_surface: string,
  leave_bottom: string,
  bottom_time: number,
  depth: number,
  decompression_completed_at: string,
  post_dive_assesment: string,
  diver_bailout_pressure: number,
  standby_diver_bailout_pressure: number,
  dive_system_id: string,
  work_description: string,
  penetration_diving: string,
  sea_state: string,
  bottom_temperature: string,
  bottom_visibility: string,
  bottom_current: string,
}